backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_devis:
    resource: "@AppBundle/Resources/config/routing/devis.yml"
    prefix:   /devis

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /manager/profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /manager/profile
