devis_index:
    path:     /
    defaults: { _controller: "AppBundle:Devis:index" }
    methods:  GET

devis_encharge:
    path:     /encharge
    defaults: { _controller: "AppBundle:Devis:finish" }
    methods:  GET

devis_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Devis:show" }
    methods:  GET

devis_new:
    path:     /new
    defaults: { _controller: "AppBundle:Devis:new" }
    methods:  [GET, POST]

devis_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Devis:edit" }
    methods:  [GET, POST]

devis_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Devis:delete" }
    methods:  DELETE
